set(HDF5_USE_STATIC_LIBRARIES 0)

find_package (HDF5 1.10 REQUIRED COMPONENTS CXX)

include_directories (SYSTEM ${HDF5_C_INCLUDE_DIRS} ${HDF5_CXX_INCLUDE_DIRS})
set(STF_LINK_LIBS ${STF_LINK_LIBS} ${HDF5_CXX_LIBRARIES})

if(STATIC_BUILD)
    set(STF_LINK_LIBS ${STF_LINK_LIBS} aec)
endif()
